BEGIN;

-- ====================================================================================
-- PHASE 1: SCHEMA CHANGES (generated by Drizzle)
-- ====================================================================================

CREATE TABLE "user_subscriptions" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"subscription_id" bigint NOT NULL,
	"activated_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "codes" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "type" varchar(30) DEFAULT 'signals' NOT NULL;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "closed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "closed_by" bigint;--> statement-breakpoint
ALTER TABLE "user_subscriptions" ADD CONSTRAINT "user_subscriptions_user_id_users_telegram_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("telegram_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_subscriptions" ADD CONSTRAINT "user_subscriptions_subscription_id_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_closed_by_managers_telegram_id_fk" FOREIGN KEY ("closed_by") REFERENCES "public"."managers"("telegram_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_subscriptions" ADD CONSTRAINT "unique_user_subscription" UNIQUE ("user_id", "subscription_id");

-- ====================================================================================
-- PHASE 2: MANUAL ENHANCEMENTS (added after Drizzle generation)
-- ====================================================================================

-- 1. Type constraint for subscription types (signals or subscription_*)
DO $$ BEGIN
  ALTER TABLE "subscriptions" ADD CONSTRAINT chk_subscription_type
  CHECK (type = 'signals' OR type LIKE 'subscription_%');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 2. Performance indexes for subscriptions table
CREATE INDEX IF NOT EXISTS idx_subscriptions_type ON subscriptions(type);
CREATE INDEX IF NOT EXISTS idx_subscriptions_type_active
  ON subscriptions(type, is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_subscriptions_is_active
  ON subscriptions(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_subscriptions_name ON subscriptions(name);
CREATE INDEX IF NOT EXISTS idx_subscriptions_broadcast
  ON subscriptions(type) WHERE type LIKE 'subscription_%';

-- 3. Performance indexes for user_subscriptions table
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user
  ON user_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_subscription
  ON user_subscriptions(subscription_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_active
  ON user_subscriptions(user_id, is_active) WHERE is_active = true;

-- 4. Performance indexes for codes table
CREATE INDEX IF NOT EXISTS idx_codes_is_active
  ON codes(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_codes_subscription_active
  ON codes(subscription_id, is_active) WHERE is_active = true;
CREATE UNIQUE INDEX IF NOT EXISTS idx_codes_code_unique_active
  ON codes(code) WHERE is_active = true AND user_id IS NULL;

-- 6. Auto-update trigger for subscriptions.updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_subscriptions_updated_at ON subscriptions;
CREATE TRIGGER update_subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 7. Set all existing subscriptions to 'signals' type
UPDATE subscriptions SET type = 'signals' WHERE type IS NULL OR type = '';

-- ====================================================================================
-- PHASE 3: DATA MIGRATION (CRITICAL - DO NOT SKIP)
-- ====================================================================================

-- STEP 1: Migrate signals subscriptions from users table
-- This moves the one-to-one relationship from users.subscribe_id to user_subscriptions
INSERT INTO user_subscriptions (user_id, subscription_id, activated_at, expires_at, is_active, created_at)
SELECT
  telegram_id,
  subscribe_id::bigint,
  created_at, -- approximate activation date (actual date unknown, use user creation date)
  subscribe_expiration_date,
  true,
  created_at
FROM users
WHERE subscribe_id IS NOT NULL
ON CONFLICT (user_id, subscription_id) DO NOTHING;

-- STEP 2: Migrate broadcast subscriptions from codes table (if any activated)
-- This moves activation data from codes.user_id/activation_date/expiration_date to user_subscriptions
INSERT INTO user_subscriptions (user_id, subscription_id, activated_at, expires_at, is_active, created_at)
SELECT
  c.user_id,
  c.subscription_id,
  COALESCE(c.activation_date, c.created_at),
  c.expiration_date,
  true,
  c.created_at
FROM codes c
WHERE c.user_id IS NOT NULL
ON CONFLICT (user_id, subscription_id) DO NOTHING;

-- ====================================================================================
-- PHASE 4: VERIFICATION (CRITICAL - MUST PASS 100%)
-- ====================================================================================

DO $$
DECLARE
  old_signals_count INT;
  new_signals_count INT;
  old_codes_count INT;
  new_codes_count INT;
BEGIN
  -- Verify signals migration
  SELECT COUNT(*) INTO old_signals_count FROM users WHERE subscribe_id IS NOT NULL;
  SELECT COUNT(*) INTO new_signals_count FROM user_subscriptions us
    INNER JOIN subscriptions s ON us.subscription_id = s.id
    WHERE s.type = 'signals';

  -- Verify codes migration
  SELECT COUNT(*) INTO old_codes_count FROM codes WHERE user_id IS NOT NULL;
  SELECT COUNT(*) INTO new_codes_count
  FROM user_subscriptions us
  WHERE EXISTS (
    SELECT 1 FROM codes c
    WHERE c.user_id = us.user_id
    AND c.subscription_id = us.subscription_id
    AND c.user_id IS NOT NULL
  );

  RAISE NOTICE '✅ Migration verification:';
  RAISE NOTICE '  - Signals: % (old) → % (new)', old_signals_count, new_signals_count;
  RAISE NOTICE '  - Codes: % (old) → % (new)', old_codes_count, new_codes_count;

  IF old_signals_count > new_signals_count THEN
    RAISE EXCEPTION 'MIGRATION FAILED: users had % signals but user_subscriptions has only %',
      old_signals_count, new_signals_count;
  END IF;

  IF old_signals_count > 0 AND new_signals_count = 0 THEN
    RAISE EXCEPTION 'CRITICAL: No data was migrated to user_subscriptions!';
  END IF;
END $$;

-- ====================================================================================
-- PHASE 5: COLUMN COMMENTS (DOCUMENTATION)
-- ====================================================================================

COMMENT ON TABLE user_subscriptions IS 'Many-to-many relationship between users and subscriptions. Replaces users.subscribeId and codes.userId/activationDate/expirationDate';
COMMENT ON COLUMN user_subscriptions.user_id IS 'Foreign key to users.telegram_id';
COMMENT ON COLUMN user_subscriptions.subscription_id IS 'Foreign key to subscriptions.id';
COMMENT ON COLUMN user_subscriptions.activated_at IS 'When the user activated this subscription (replaces codes.activationDate)';
COMMENT ON COLUMN user_subscriptions.expires_at IS 'When the subscription expires (replaces users.subscribeExpirationDate and codes.expirationDate)';
COMMENT ON COLUMN user_subscriptions.is_active IS 'Whether this subscription relationship is active';

COMMENT ON COLUMN subscriptions.type IS 'Subscription type: "signals" for automated trading signals or "subscription_{uid}" for broadcast subscriptions';
COMMENT ON COLUMN subscriptions.is_active IS 'Subscription active status (soft delete). When false, associated codes are invalidated';
COMMENT ON COLUMN subscriptions.updated_at IS 'Last modification timestamp (auto-updated by trigger)';
COMMENT ON COLUMN subscriptions.closed_at IS 'When the subscription was closed/deactivated';
COMMENT ON COLUMN subscriptions.closed_by IS 'Manager who closed the subscription (audit trail)';

COMMENT ON COLUMN codes.is_active IS 'Code active status. Invalidated when subscription is closed';

COMMIT;