-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "managers" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"username" varchar DEFAULT '100',
	"telegram_id" bigint PRIMARY KEY NOT NULL,
	"lang" varchar DEFAULT '10',
	"first_name" varchar DEFAULT '255',
	"last_name" varchar DEFAULT '255',
	"is_premium" boolean DEFAULT false,
	"is_active" boolean NOT NULL
);
--> statement-breakpoint
ALTER TABLE "managers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "orders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"symbol" varchar DEFAULT '20' NOT NULL,
	"order_type" varchar DEFAULT '20' NOT NULL,
	"lots" real NOT NULL,
	"open_price" real NOT NULL,
	"close_price" real,
	"stop_loss" real,
	"take_profit" real,
	"profit" real,
	"ticket_id" integer NOT NULL,
	"close_time" timestamp
);
--> statement-breakpoint
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lang" varchar DEFAULT '10',
	"message" text,
	"type" varchar DEFAULT '10'
);
--> statement-breakpoint
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "codes" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"code" varchar NOT NULL,
	"subscription_id" bigint NOT NULL,
	"activation_date" timestamp,
	"user_id" bigint,
	"expiration_date" timestamp
);
--> statement-breakpoint
ALTER TABLE "codes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar NOT NULL,
	"scope" jsonb
);
--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"username" varchar DEFAULT '100',
	"telegram_id" bigint PRIMARY KEY NOT NULL,
	"lang" varchar DEFAULT '10',
	"first_name" varchar DEFAULT '255',
	"last_name" varchar DEFAULT '255',
	"is_premium" boolean DEFAULT false,
	"subscribe_expiration_date" timestamp with time zone,
	"subscribe_id" integer
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "summary" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "summary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"result" real NOT NULL
);
--> statement-breakpoint
ALTER TABLE "summary" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "codes" ADD CONSTRAINT "codes_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "codes" ADD CONSTRAINT "codes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("telegram_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_subscribe_id_fkey" FOREIGN KEY ("subscribe_id") REFERENCES "public"."subscriptions"("id") ON DELETE no action ON UPDATE no action;
*/